import '/styles/globals.scss';

import MainHeader from '@/components/Layout/MainHeader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
