import '@/styles/globals.scss'

import React from 'react'

import MainHeader from '@/components/layouts/MainHeader'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="ko"
      data-scroll-container
      className="has-scroll-init has-scroll-smooth has-scroll-dragging"
    >
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  )
}
